services:
  worker:
    image: ghcr.io/ver-1000000/butler:latest
    command: npm run prod:worker
    environment:
      NODE_ENV: "production"
    volumes:
      - butler-data:/app/data
  web:
    image: ghcr.io/ver-1000000/butler:latest
    command: npm run prod:web
    environment:
      NODE_ENV: "production"
    volumes:
      - butler-data:/app/data
    ports:
      - "3000:3000"

volumes:
  butler-data:
