services:
  worker:
    image: ghcr.io/ver-1000000/butler-worker:latest
    command: npm run prod:worker
    environment:
      NODE_ENV: "production"
      # 必須の環境変数はcompose.override.yamlで設定する
    volumes:
      - butler-data:/app/data
  web:
    image: ghcr.io/ver-1000000/butler-web:latest
    command: npm run prod:web
    environment:
      NODE_ENV: "production"
      # 必須の環境変数はcompose.override.yamlで設定する
    volumes:
      - butler-data:/app/data
    ports:
      - "3000:3000"

volumes:
  butler-data:
